### ISSUE TITLE
Failing on fresh Ubuntu installs due to missing dependencies

### ISSUE THREAD

**Issue by epiccurious** [JWWeatherman/yeticold#178]
Running Yeti 3 from the head of master on a fresh install of Ubuntu 20, 22, and 24 LTS  is currently broken.

Pastebin for Ubuntu 20 LTS: [pastebin.com/4NwFU2q5](pastebin.com/4NwFU2q5)
Pastebin for Ubuntu 22 LTS: [pastebin.com/Mj4zc1ra](pastebin.com/Mj4zc1ra)
Pastebin for Ubuntu 24 LTS: [pastebin.com/fDP72QKX](pastebin.com/fDP72QKX)

On Ubuntu 20 and 22, apt-get is failing to install pip, which is causing flask to fail:
```
E: Package 'python3-pip' has no installation candidate
E: Package 'tor' has no installation candidate
E: Package 'brasero' has no installation candidate
...
********************
Running Yeti Level Three on Primary PC
********************
 
Traceback (most recent call last):
  File "/home/ubuntu/yeticold/appyeticold.py", line 5, in <module>
    from btcrpcfunctions import blockheight
  File "/home/ubuntu/yeticold/utils/btcrpcfunctions.py", line 1, in <module>
    from imports import *
  File "/home/ubuntu/yeticold/utils/imports.py", line 1, in <module>
    from flask import Flask, render_template, redirect, url_for, request
ModuleNotFoundError: No module named 'flask'
ubuntu@ubuntu:~$ [GFX1-]: glxtest: VA-API test failed: missing or old libva-drm library.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
ATTENTION: default value of option mesa_glthread overridden by environment.
```

On Ubuntu 24, apt-get is throwing this error multiple times:
```
Processing triggers for libc-bin (2.39-0ubuntu8) ...
error: externally-managed-environment
 
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
```

**Comment by epiccurious** [comment]
The externally managed environment was fixed with someone adding this to three.yeticold.com
```
python3 -m venv ~/my_env && source ~/my_env/bin/activate && 
```

But there's still another issue - the bip32 pip module isn't installing because the version 3.1 doesn't exist in the pip repository. [Here are the failure logs.](https://pastebin.com/nisi8Xh4).

The fix for the bip32 issue is to bump the version to 3.4, which is the default for `pip install bip32`.

**Comment by epiccurious** [comment]
Reducing the scope of this ticket to just bip32 issues, since the venv stuff was worked on on the yetihosted repo.
